#!/bin/bash
target=$1
if [ -z "$target" ]; then
    echo -e "\033[1;31m[!] تکایە ناوی ماڵپەڕێک بنووسە. نموونە: pasha-scan google.com\033[0m"
    exit 1
fi
echo -e "\033[1;33m[!] Starting Scan on: $target\033[0m"
nmap -sV -F $target
echo -e "\033[1;32m[+] Scan Completed!\033[0m"
